package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"fmt"
	"time"

	"github.com/KennyTheBard/go-books-graphql-api/db"
	"github.com/KennyTheBard/go-books-graphql-api/graph/dataloaders"
	"github.com/KennyTheBard/go-books-graphql-api/graph/model"
	"github.com/KennyTheBard/go-books-graphql-api/utils"
	"github.com/graph-gophers/dataloader/v6"
	"go.uber.org/zap"
)

// CreateBook is the resolver for the createBook field.
func (r *mutationResolver) CreateBook(ctx context.Context, input model.NewBook) (*model.Book, error) {
	publishDate, err := time.Parse(utils.JavascriptDateTimeFormat, input.PublishDate)
	if err != nil {
		return nil, err
	}

	var author db.Author
	if err = r.DB.First(&author, input.AuthorID).Error; err != nil {
		return nil, err
	}

	book := &db.Book{
		Title:       input.Title,
		AuthorID:    input.AuthorID,
		PublishDate: publishDate,
	}
	if err = r.DB.Create(book).Error; err != nil {
		return nil, err
	}

	return &model.Book{
		ID:    book.ID,
		Title: book.Title,
		Author: &model.Author{
			ID:          author.ID,
			Name:        author.Name,
			DateOfBirth: author.DateOfBirth.Format(utils.JavascriptDateTimeFormat),
		},
		PublishDate: book.PublishDate.Format(utils.JavascriptDateTimeFormat),
	}, nil
}

// CreateAuthor is the resolver for the createAuthor field.
func (r *mutationResolver) CreateAuthor(ctx context.Context, input model.NewAuthor) (*model.Author, error) {
	dateOfBirth, err := time.Parse(utils.JavascriptDateTimeFormat, input.DateOfBirth)
	if err != nil {
		return nil, err
	}

	author := &db.Author{
		Name:        input.Name,
		DateOfBirth: dateOfBirth,
	}
	if err = r.DB.Create(author).Error; err != nil {
		return nil, err
	}

	r.Logger.Info("Created Author", zap.Any("author", *author))
	return &model.Author{
		ID:          author.ID,
		Name:        author.Name,
		DateOfBirth: author.DateOfBirth.Format(utils.JavascriptDateTimeFormat),
	}, nil
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context) ([]*model.Book, error) {
	var books []db.Book
	if err := r.DB.Find(&books).Error; err != nil {
		return nil, err
	}

	authorIds := make([]dataloader.Key, len(books))
	for index, book := range books {
		authorIds[index] = dataloader.StringKey(fmt.Sprintf("%v", book.AuthorID))
	}

	loaders := dataloaders.GetLoaders(ctx)
	getAuthors := loaders.AuthorLoader.LoadMany(ctx, authorIds)
	results, errs := getAuthors()
	for _, err := range errs {
		if err != nil {
			return nil, err
		}
	}
	authors := make([]*db.Author, len(results))
	for index, author := range results {
		authors[index] = author.(*db.Author)
	}

	bookModels := make([]*model.Book, len(books))
	for index, book := range books {
		author := authors[index]
		bookModels[index] = &model.Book{
			ID:          book.ID,
			Title:       book.Title,
			PublishDate: book.PublishDate.Format(utils.JavascriptDateTimeFormat),
			Author: &model.Author{
				ID:          author.ID,
				Name:        author.Name,
				DateOfBirth: author.DateOfBirth.Format(utils.JavascriptDateTimeFormat),
			},
		}
	}
	return bookModels, nil
}

// BookByID is the resolver for the bookById field.
func (r *queryResolver) BookByID(ctx context.Context, id int) (*model.Book, error) {
	var book db.Book
	if err := r.DB.First(&book, id).Error; err != nil {
		return nil, err
	}

	loaders := dataloaders.GetLoaders(ctx)
	getBook := loaders.AuthorLoader.Load(ctx, dataloader.StringKey(fmt.Sprintf("%v", book.AuthorID)))
	result, err := getBook()
	if err != nil {
		return nil, err
	}

	author := result.(*db.Author)
	return &model.Book{
		ID:          book.ID,
		Title:       book.Title,
		PublishDate: book.PublishDate.Format(utils.JavascriptDateTimeFormat),
		Author: &model.Author{
			ID:          author.ID,
			Name:        author.Name,
			DateOfBirth: author.DateOfBirth.Format(utils.JavascriptDateTimeFormat),
		},
	}, nil
}

// Authors is the resolver for the authors field.
func (r *queryResolver) Authors(ctx context.Context) ([]*model.Author, error) {
	var authors []db.Author
	if err := r.DB.Find(&authors).Error; err != nil {
		return nil, err
	}

	authorModels := make([]*model.Author, len(authors))
	for i, author := range authors {
		authorModels[i] = &model.Author{
			ID:          author.ID,
			Name:        author.Name,
			DateOfBirth: author.DateOfBirth.Format(utils.JavascriptDateTimeFormat),
		}
	}
	return authorModels, nil
}

// AuthorByID is the resolver for the authorById field.
func (r *queryResolver) AuthorByID(ctx context.Context, id int) (*model.Author, error) {
	var author db.Author
	if err := r.DB.First(&author, id).Error; err != nil {
		return nil, err
	}

	return &model.Author{
		ID:          author.ID,
		Name:        author.Name,
		DateOfBirth: author.DateOfBirth.Format(utils.JavascriptDateTimeFormat),
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
