// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	DateOfBirth string `json:"dateOfBirth"`
}

type Book struct {
	ID          int     `json:"id"`
	Title       string  `json:"title"`
	Author      *Author `json:"author"`
	PublishDate string  `json:"publishDate"`
}

type NewAuthor struct {
	Name        string `json:"name"`
	DateOfBirth string `json:"dateOfBirth"`
}

type NewBook struct {
	Title       string `json:"title"`
	AuthorID    int    `json:"authorId"`
	PublishDate string `json:"publishDate"`
}
